# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMgmt', '0003_order_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
