# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMgmt', '0004_auto_20190516_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
    ]
