# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=60)),
                ('option2', models.CharField(max_length=60)),
                ('option3', models.CharField(max_length=60)),
                ('option4', models.CharField(max_length=60)),
                ('answer', models.CharField(max_length=60)),
                ('marks', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Standard_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='standard_subject',
            name='subject',
            field=models.ManyToManyField(to='subjecttest.Subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='std_sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.Standard_Subject'),
        ),
    ]
