# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjecttest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='std_sub_id',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
