# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjecttest', '0002_auto_20190621_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=60)),
                ('option2', models.CharField(max_length=60)),
                ('option3', models.CharField(max_length=60)),
                ('option4', models.CharField(max_length=60)),
                ('answer', models.CharField(max_length=60)),
                ('marks', models.PositiveIntegerField()),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.Standard_Subject')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.Subject')),
            ],
        ),
    ]
